name: CI Pipeline

# When does this run?
on:
  push:
    branches: [feature/backend, feature/frontend, dev]
  pull_request:
    branches: [dev, main]

jobs:
  backend-ci:
    name: Backend Checks
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Check out your code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2 - Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      # Step 3 - Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: backend

      # Step 4 - Run ESLint
      - name: Lint code
        run: npm run lint
        working-directory: backend

      # Step 5 - Run tests
      - name: Run tests
        run: npm test
        working-directory: backend
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}